package scripts.util.names.type;

import scripts.util.misc.ItemWrapper;
import scripts.util.misc.NameFormatter;
import scripts.util.names.ItemIds;
import scripts.util.names.ItemNames;

public enum SmithableType implements ItemWrapper {
	BRONZE_DAGGER(ItemNames.BRONZE_DAGGER, 			1, BarType.BRONZE_BAR, 1),
	BRONZE_AXE(ItemNames.BRONZE_AXE, 				1, BarType.BRONZE_BAR, 1),
	BRONZE_MACE(ItemNames.BRONZE_MACE, 				2, BarType.BRONZE_BAR, 1),
	BRONZE_MED_HELM(ItemNames.BRONZE_MED_HELM, 		3, BarType.BRONZE_BAR, 1),
	BRONZE_SWORD(ItemNames.BRONZE_SWORD, 			4, BarType.BRONZE_BAR, 1),
	BRONZE_SCIMITAR(ItemNames.BRONZE_SCIMITAR, 		5, BarType.BRONZE_BAR, 2),
	BRONZE_LONGSWORD(ItemNames.BRONZE_LONGSWORD,	6, BarType.BRONZE_BAR, 2),
	BRONZE_FULL_HELM(ItemNames.BRONZE_FULL_HELM,	7, BarType.BRONZE_BAR, 2),
	BRONZE_SQ_SHIELD(ItemNames.BRONZE_SQ_SHIELD,	8, BarType.BRONZE_BAR, 2),
	BRONZE_WARHAMMER(ItemNames.BRONZE_WARHAMMER,	9, BarType.BRONZE_BAR, 3),
	BRONZE_BATTLEAXE(ItemNames.BRONZE_BATTLEAXE,	10, BarType.BRONZE_BAR, 3),
	BRONZE_CHAINBODY(ItemNames.BRONZE_CHAINBODY,	11, BarType.BRONZE_BAR, 3),
	BRONZE_KITESHIELD(ItemNames.BRONZE_KITESHIELD,	12, BarType.BRONZE_BAR, 3),
	BRONZE_2H_SWORD(ItemNames.BRONZE_2H_SWORD,	    14, BarType.BRONZE_BAR, 3),
	BRONZE_PLATELEGS(ItemNames.BRONZE_PLATELEGS,	16, BarType.BRONZE_BAR, 3),
	BRONZE_PLATESKIRT(ItemNames.BRONZE_PLATESKIRT,	16, BarType.BRONZE_BAR, 3),
	BRONZE_PLATEBODY(ItemNames.BRONZE_PLATEBODY,	18, BarType.BRONZE_BAR, 5),
	
	IRON_DAGGER(ItemNames.IRON_DAGGER, 			15, BarType.IRON_BAR, 1),
	IRON_AXE(ItemNames.IRON_AXE, 				16, BarType.IRON_BAR, 1),
	IRON_MACE(ItemNames.IRON_MACE, 				17, BarType.IRON_BAR, 1),
	IRON_MED_HELM(ItemNames.IRON_MED_HELM, 		18, BarType.IRON_BAR, 1),
	IRON_SWORD(ItemNames.IRON_SWORD, 			19, BarType.IRON_BAR, 1),
	IRON_SCIMITAR(ItemNames.IRON_SCIMITAR, 		20, BarType.IRON_BAR, 2),
	IRON_LONGSWORD(ItemNames.IRON_LONGSWORD,	21, BarType.IRON_BAR, 2),
	IRON_FULL_HELM(ItemNames.IRON_FULL_HELM,	22, BarType.IRON_BAR, 2),
	IRON_SQ_SHIELD(ItemNames.IRON_SQ_SHIELD,	23, BarType.IRON_BAR, 2),
	IRON_WARHAMMER(ItemNames.IRON_WARHAMMER,	24, BarType.IRON_BAR, 3),
	IRON_BATTLEAXE(ItemNames.IRON_BATTLEAXE,	25, BarType.IRON_BAR, 3),
	IRON_CHAINBODY(ItemNames.IRON_CHAINBODY,	26, BarType.IRON_BAR, 3),
	IRON_KITESHIELD(ItemNames.IRON_KITESHIELD,	27, BarType.IRON_BAR, 3),
	IRON_2H_SWORD(ItemNames.IRON_2H_SWORD,	    29, BarType.IRON_BAR, 3),
	IRON_PLATELEGS(ItemNames.IRON_PLATELEGS,	31, BarType.IRON_BAR, 3),
	IRON_PLATESKIRT(ItemNames.IRON_PLATESKIRT,	31, BarType.IRON_BAR, 3),
	IRON_PLATEBODY(ItemNames.IRON_PLATEBODY,	33, BarType.IRON_BAR, 5),
	
	STEEL_DAGGER(ItemNames.STEEL_DAGGER, 			30, BarType.STEEL_BAR, 1),
	STEEL_AXE(ItemNames.STEEL_AXE, 					31, BarType.STEEL_BAR, 1),
	STEEL_MACE(ItemNames.STEEL_MACE, 				32, BarType.STEEL_BAR, 1),
	STEEL_MED_HELM(ItemNames.STEEL_MED_HELM, 		33, BarType.STEEL_BAR, 1),
	STEEL_SWORD(ItemNames.STEEL_SWORD, 				34, BarType.STEEL_BAR, 1),
	STEEL_SCIMITAR(ItemNames.STEEL_SCIMITAR, 		35, BarType.STEEL_BAR, 2),
	STEEL_LONGSWORD(ItemNames.STEEL_LONGSWORD,		36, BarType.STEEL_BAR, 2),
	STEEL_FULL_HELM(ItemNames.STEEL_FULL_HELM,	    37, BarType.STEEL_BAR, 2),
	STEEL_SQ_SHIELD(ItemNames.STEEL_SQ_SHIELD,	    38, BarType.STEEL_BAR, 2),
	STEEL_WARHAMMER(ItemNames.STEEL_WARHAMMER,	    39, BarType.STEEL_BAR, 3),
	STEEL_BATTLEAXE(ItemNames.STEEL_BATTLEAXE,	    40, BarType.STEEL_BAR, 3),
	STEEL_CHAINBODY(ItemNames.STEEL_CHAINBODY,	    41, BarType.STEEL_BAR, 3),
	STEEL_KITESHIELD(ItemNames.STEEL_KITESHIELD,	42, BarType.STEEL_BAR, 3),
	STEEL_2H_SWORD(ItemNames.STEEL_2H_SWORD,	    44, BarType.STEEL_BAR, 3),
	STEEL_PLATELEGS(ItemNames.STEEL_PLATELEGS,	    46, BarType.STEEL_BAR, 3),
	STEEL_PLATESKIRT(ItemNames.STEEL_PLATESKIRT,	46, BarType.STEEL_BAR, 3),
	STEEL_PLATEBODY(ItemNames.STEEL_PLATEBODY,	    48, BarType.STEEL_BAR, 5),
	
	MITHRIL_DAGGER(ItemNames.MITHRIL_DAGGER, 			50, BarType.MITHRIL_BAR, 1),
	MITHRIL_AXE(ItemNames.MITHRIL_AXE, 					51, BarType.MITHRIL_BAR, 1),
	MITHRIL_MACE(ItemNames.MITHRIL_MACE, 				52, BarType.MITHRIL_BAR, 1),
	MITHRIL_MED_HELM(ItemNames.MITHRIL_MED_HELM, 		53, BarType.MITHRIL_BAR, 1),
	MITHRIL_SWORD(ItemNames.MITHRIL_SWORD, 				54, BarType.MITHRIL_BAR, 1),
	MITHRIL_SCIMITAR(ItemNames.MITHRIL_SCIMITAR, 		55, BarType.MITHRIL_BAR, 2),
	MITHRIL_LONGSWORD(ItemNames.MITHRIL_LONGSWORD,		56, BarType.MITHRIL_BAR, 2),
	MITHRIL_FULL_HELM(ItemNames.MITHRIL_FULL_HELM,	    57, BarType.MITHRIL_BAR, 2),
	MITHRIL_SQ_SHIELD(ItemNames.MITHRIL_SQ_SHIELD,	    58, BarType.MITHRIL_BAR, 2),
	MITHRIL_WARHAMMER(ItemNames.MITHRIL_WARHAMMER,	    59, BarType.MITHRIL_BAR, 3),
	MITHRIL_BATTLEAXE(ItemNames.MITHRIL_BATTLEAXE,	    60, BarType.MITHRIL_BAR, 3),
	MITHRIL_CHAINBODY(ItemNames.MITHRIL_CHAINBODY,	    61, BarType.MITHRIL_BAR, 3),
	MITHRIL_KITESHIELD(ItemNames.MITHRIL_KITESHIELD,	62, BarType.MITHRIL_BAR, 3),
	MITHRIL_2H_SWORD(ItemNames.MITHRIL_2H_SWORD,	    64, BarType.MITHRIL_BAR, 3),
	MITHRIL_PLATELEGS(ItemNames.MITHRIL_PLATELEGS,	    66, BarType.MITHRIL_BAR, 3),
	MITHRIL_PLATESKIRT(ItemNames.MITHRIL_PLATESKIRT,	66, BarType.MITHRIL_BAR, 3),
	MITHRIL_PLATEBODY(ItemNames.MITHRIL_PLATEBODY,	    68, BarType.MITHRIL_BAR, 5),
	
	ADAMANT_DAGGER(ItemNames.ADAMANT_DAGGER, 			70, BarType.ADAMANT_BAR, 1),
	ADAMANT_AXE(ItemNames.ADAMANT_AXE, 					71, BarType.ADAMANT_BAR, 1),
	ADAMANT_MACE(ItemNames.ADAMANT_MACE, 				72, BarType.ADAMANT_BAR, 1),
	ADAMANT_MED_HELM(ItemNames.ADAMANT_MED_HELM, 		73, BarType.ADAMANT_BAR, 1),
	ADAMANT_SWORD(ItemNames.ADAMANT_SWORD, 				74, BarType.ADAMANT_BAR, 1),
	ADAMANT_SCIMITAR(ItemNames.ADAMANT_SCIMITAR, 		75, BarType.ADAMANT_BAR, 2),
	ADAMANT_LONGSWORD(ItemNames.ADAMANT_LONGSWORD,		76, BarType.ADAMANT_BAR, 2),
	ADAMANT_FULL_HELM(ItemNames.ADAMANT_FULL_HELM,	    77, BarType.ADAMANT_BAR, 2),
	ADAMANT_SQ_SHIELD(ItemNames.ADAMANT_SQ_SHIELD,	    78, BarType.ADAMANT_BAR, 2),
	ADAMANT_WARHAMMER(ItemNames.ADAMANT_WARHAMMER,	    79, BarType.ADAMANT_BAR, 3),
	ADAMANT_BATTLEAXE(ItemNames.ADAMANT_BATTLEAXE,	    80, BarType.ADAMANT_BAR, 3),
	ADAMANT_CHAINBODY(ItemNames.ADAMANT_CHAINBODY,	    81, BarType.ADAMANT_BAR, 3),
	ADAMANT_KITESHIELD(ItemNames.ADAMANT_KITESHIELD,	82, BarType.ADAMANT_BAR, 3),
	ADAMANT_2H_SWORD(ItemNames.ADAMANT_2H_SWORD,	    84, BarType.ADAMANT_BAR, 3),
	ADAMANT_PLATELEGS(ItemNames.ADAMANT_PLATELEGS,	    86, BarType.ADAMANT_BAR, 3),
	ADAMANT_PLATESKIRT(ItemNames.ADAMANT_PLATESKIRT,	86, BarType.ADAMANT_BAR, 3),
	ADAMANT_PLATEBODY(ItemNames.ADAMANT_PLATEBODY,	    88, BarType.ADAMANT_BAR, 5),
	
	RUNE_DAGGER(ItemNames.RUNE_DAGGER, 				85, BarType.RUNE_BAR, 1),
	RUNE_AXE(ItemNames.RUNE_AXE, 					86, BarType.RUNE_BAR, 1),
	RUNE_MACE(ItemNames.RUNE_MACE, 					87, BarType.RUNE_BAR, 1),
	RUNE_MED_HELM(ItemNames.RUNE_MED_HELM, 			88, BarType.RUNE_BAR, 1),
	RUNE_SWORD(ItemNames.RUNE_SWORD, 				89, BarType.RUNE_BAR, 1),
	RUNE_SCIMITAR(ItemNames.RUNE_SCIMITAR, 			90, BarType.RUNE_BAR, 2),
	RUNE_LONGSWORD(ItemNames.RUNE_LONGSWORD,		91, BarType.RUNE_BAR, 2),
	RUNE_FULL_HELM(ItemNames.RUNE_FULL_HELM,	    92, BarType.RUNE_BAR, 2),
	RUNE_SQ_SHIELD(ItemNames.RUNE_SQ_SHIELD,	    93, BarType.RUNE_BAR, 2),
	RUNE_WARHAMMER(ItemNames.RUNE_WARHAMMER,	    94, BarType.RUNE_BAR, 3),
	RUNE_BATTLEAXE(ItemNames.RUNE_BATTLEAXE,	    95, BarType.RUNE_BAR, 3),
	RUNE_CHAINBODY(ItemNames.RUNE_CHAINBODY,	    96, BarType.RUNE_BAR, 3),
	RUNE_KITESHIELD(ItemNames.RUNE_KITESHIELD,		97, BarType.RUNE_BAR, 3),
	RUNE_2H_SWORD(ItemNames.RUNE_2H_SWORD,	    	99, BarType.RUNE_BAR, 3),
	RUNE_PLATELEGS(ItemNames.RUNE_PLATELEGS,	    99, BarType.RUNE_BAR, 3),
	RUNE_PLATESKIRT(ItemNames.RUNE_PLATESKIRT,	    99, BarType.RUNE_BAR, 3),
	RUNE_PLATEBODY(ItemNames.RUNE_PLATEBODY,	    99, BarType.RUNE_BAR, 5),
	;
	
	private ItemIds item;
	private int requiredSmithingLevel;
	private BarType requiredBarType;
	private int requiredBarAmount;
	
	SmithableType(ItemIds item, int level, BarType requiredBar, int amountBars) {
		this.item = item;
		this.requiredSmithingLevel = level;
		this.requiredBarType = requiredBar;
	}
	
	public BarType getRequiredBarType() {
		return this.requiredBarType;
	}
	
	public int getRequiredBarAmount() {
		return this.requiredBarAmount;
	}
	
	public int getRequiredSmithingLevel() {
		return this.requiredSmithingLevel;
	}
	
	@Override
	public ItemIds getItem() {
		return this.item;
	}

	public String getName() {
		return NameFormatter.formatItemName(this.toString());
	}

}
